name: SNOW Create Standard Change

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Create Standard Change
        env:
          SN_INSTANCE: ${{ secrets.SN_INSTANCE }}
          SN_USERNAME: ${{ secrets.SN_USERNAME }}
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
          SN_STD_TEMPLATE_SYSID: ${{ secrets.SN_STD_TEMPLATE_SYSID }}
        run: python scripts/servicenow/create_std_change.py